
	CREATE TABLE universities(
		id SERIAL,
		code TEXT,
		name TEXT,
		city TEXT,
		type TEXT,
			UNIQUE(code)
	);
	INSERT INTO universities (code, name, city, type) VALUES
('ted-universitesi', 'TED ÜNİVERSİTESİ', 'ANKARA', 'VAKIF'),
('bayburt-universitesi', 'BAYBURT ÜNİVERSİTESİ', 'BAYBURT', 'DEVLET'),
('erzurum-teknik-universitesi', 'ERZURUM TEKNİK ÜNİVERSİTESİ', 'ERZURUM', 'DEVLET'),
('istanbul-yeni-yuzyil-universitesi', 'İSTANBUL YENİ YÜZYIL ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('dokuz-eylul-universitesi', 'DOKUZ EYLÜL ÜNİVERSİTESİ', 'İZMİR', 'DEVLET'),
('eskisehir-osmangazi-universitesi', 'ESKİŞEHİR OSMANGAZİ ÜNİVERSİTESİ', 'ESKİŞEHİR', 'DEVLET'),
('suleyman-demirel-universitesi', 'SÜLEYMAN DEMİREL ÜNİVERSİTESİ', 'ISPARTA', 'DEVLET'),
('ufuk-universitesi', 'UFUK ÜNİVERSİTESİ', 'ANKARA', 'VAKIF'),
('baskent-universitesi', 'BAŞKENT ÜNİVERSİTESİ', 'ADANA', 'VAKIF'),
('igdir-universitesi', 'IĞDIR ÜNİVERSİTESİ', 'IĞDIR', 'DEVLET'),
('isik-universitesi', 'IŞIK ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('uskudar-universitesi', 'ÜSKÜDAR ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('ihsan-dogramaci-bilkent-universitesi', 'İHSAN DOĞRAMACI BİLKENT ÜNİVERSİTESİ', 'ANKARA', 'VAKIF'),
('kirklareli-universitesi', 'KIRKLARELİ ÜNİVERSİTESİ', 'KIRKLARELİ', 'DEVLET'),
('nuh-naci-yazgan-universitesi', 'NUH NACİ YAZGAN ÜNİVERSİTESİ', 'KAYSERİ', 'VAKIF'),
('saglik-bilimleri-universitesi', 'SAĞLIK BİLİMLERİ ÜNİVERSİTESİ', 'ADANA', 'DEVLET'),
('yasar-universitesi', 'YAŞAR ÜNİVERSİTESİ', 'İZMİR', 'VAKIF'),
('atasehir-adiguzel-meslek-yuksekokulu', 'ATAŞEHİR ADIGÜZEL MESLEK YÜKSEKOKULU', 'İSTANBUL', 'VAKIF   MYO'),
('bahcesehir-universitesi', 'BAHÇEŞEHİR ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('balikesir-universitesi', 'BALIKESİR ÜNİVERSİTESİ', 'BALIKESİR', 'DEVLET'),
('anka-teknoloji-universitesi', 'ANKA TEKNOLOJİ ÜNİVERSİTESİ', 'ANKARA', 'VAKIF'),
('ankara-universitesi', 'ANKARA ÜNİVERSİTESİ', 'ANKARA', 'DEVLET'),
('istanbul-galata-universitesi', 'İSTANBUL GALATA ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('aksaray-universitesi', 'AKSARAY ÜNİVERSİTESİ', 'AKSARAY', 'DEVLET'),
('izmir-kavram-meslek-yuksekokulu', 'İZMİR KAVRAM MESLEK YÜKSEKOKULU', 'İZMİR', 'VAKIF   MYO'),
('van-yuzuncu-yil-universitesi', 'VAN YÜZÜNCÜ YIL ÜNİVERSİTESİ', 'VAN', 'DEVLET'),
('demiroglu-bilim-universitesi', 'DEMİROĞLU BİLİM ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('istanbul-esenyurt-universitesi', 'İSTANBUL ESENYURT ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('istanbul-gelisim-universitesi', 'İSTANBUL GELİŞİM ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('kocaeli-universitesi', 'KOCAELİ ÜNİVERSİTESİ', 'KOCAELİ', 'DEVLET'),
('firat-universitesi', 'FIRAT ÜNİVERSİTESİ', 'ELAZIĞ', 'DEVLET'),
('halic-universitesi', 'HALİÇ ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('hatay-mustafa-kemal-universitesi', 'HATAY MUSTAFA KEMAL ÜNİVERSİTESİ', 'HATAY', 'DEVLET'),
('sabanci-universitesi', 'SABANCI ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('tekirdag-namik-kemal-universitesi', 'TEKİRDAĞ NAMIK KEMAL ÜNİVERSİTESİ', 'TEKİRDAĞ', 'DEVLET'),
('istanbul-arel-universitesi', 'İSTANBUL AREL ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('istanbul-medeniyet-universitesi', 'İSTANBUL MEDENİYET ÜNİVERSİTESİ', 'İSTANBUL', 'DEVLET'),
('mimar-sinan-guzel-sanatlar-universitesi', 'MİMAR SİNAN GÜZEL SANATLAR ÜNİVERSİTESİ', 'İSTANBUL', 'DEVLET'),
('yalova-universitesi', 'YALOVA ÜNİVERSİTESİ', 'YALOVA', 'DEVLET'),
('bandirma-onyedi-eylul-universitesi', 'BANDIRMA ONYEDİ EYLÜL ÜNİVERSİTESİ', 'BALIKESİR', 'DEVLET'),
('istanbul-bilgi-universitesi', 'İSTANBUL BİLGİ ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('kadir-has-universitesi', 'KADİR HAS ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('burdur-mehmet-akif-ersoy-universitesi', 'BURDUR MEHMET AKİF ERSOY ÜNİVERSİTESİ', 'BURDUR', 'DEVLET'),
('aydin-adnan-menderes-universitesi', 'AYDIN ADNAN MENDERES ÜNİVERSİTESİ', 'AYDIN', 'DEVLET'),
('siirt-universitesi', 'SİİRT ÜNİVERSİTESİ', 'SİİRT', 'DEVLET'),
('iskenderun-teknik-universitesi', 'İSKENDERUN TEKNİK ÜNİVERSİTESİ', 'HATAY', 'DEVLET'),
('kapadokya-universitesi', 'KAPADOKYA ÜNİVERSİTESİ', 'NEVŞEHİR', 'VAKIF'),
('kastamonu-universitesi', 'KASTAMONU ÜNİVERSİTESİ', 'KASTAMONU', 'DEVLET'),
('istanbul-beykent-universitesi', 'İSTANBUL BEYKENT ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('alanya-alaaddin-keykubat-universitesi', 'ALANYA ALAADDİN KEYKUBAT ÜNİVERSİTESİ', 'ANTALYA', 'DEVLET'),
('bingol-universitesi', 'BİNGÖL ÜNİVERSİTESİ', 'BİNGÖL', 'DEVLET'),
('nevsehir-haci-bektas-veli-universitesi', 'NEVŞEHİR HACI BEKTAŞ VELİ ÜNİVERSİTESİ', 'NEVŞEHİR', 'DEVLET'),
('karadeniz-teknik-universitesi', 'KARADENİZ TEKNİK ÜNİVERSİTESİ', 'TRABZON', 'DEVLET'),
('mef-universitesi', 'MEF ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('canakkale-onsekiz-mart-universitesi', 'ÇANAKKALE ONSEKİZ MART ÜNİVERSİTESİ', 'ÇANAKKALE', 'DEVLET'),
('orta-dogu-teknik-universitesi', 'ORTA DOĞU TEKNİK ÜNİVERSİTESİ', 'ANKARA', 'DEVLET'),
('ozyegin-universitesi', 'ÖZYEĞİN ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('ege-universitesi', 'EGE ÜNİVERSİTESİ', 'İZMİR', 'DEVLET'),
('anadolu-universitesi', 'ANADOLU ÜNİVERSİTESİ', 'ESKİŞEHİR', 'DEVLET'),
('kto-karatay-universitesi', 'KTO KARATAY ÜNİVERSİTESİ', 'KONYA', 'VAKIF'),
('piri-reis-universitesi', 'PİRİ REİS ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('yuksek-ihtisas-universitesi', 'YÜKSEK İHTİSAS ÜNİVERSİTESİ', 'ANKARA', 'VAKIF'),
('bartin-universitesi', 'BARTIN ÜNİVERSİTESİ', 'BARTIN', 'DEVLET'),
('hitit-universitesi', 'HİTİT ÜNİVERSİTESİ', 'ÇORUM', 'DEVLET'),
('tobb-ekonomi-ve-teknoloji-universitesi', 'TOBB EKONOMİ VE TEKNOLOJİ ÜNİVERSİTESİ', 'ANKARA', 'VAKIF'),
('amasya-universitesi', 'AMASYA ÜNİVERSİTESİ', 'AMASYA', 'DEVLET'),
('kahramanmaras-istiklal-universitesi', 'KAHRAMANMARAŞ İSTİKLAL ÜNİVERSİTESİ', 'KAHRAMANMARAŞ', 'DEVLET'),
('zonguldak-bulent-ecevit-universitesi', 'ZONGULDAK BÜLENT ECEVİT ÜNİVERSİTESİ', 'ZONGULDAK', 'DEVLET'),
('koc-universitesi', 'KOÇ ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('alanya-universitesi', 'ALANYA ÜNİVERSİTESİ', 'ANTALYA', 'VAKIF'),
('istanbul-aydin-universitesi', 'İSTANBUL AYDIN ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('istanbul-universitesi', 'İSTANBUL ÜNİVERSİTESİ', 'İSTANBUL', 'DEVLET'),
('maltepe-universitesi', 'MALTEPE ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('hakkari-universitesi', 'HAKKARİ ÜNİVERSİTESİ', 'HAKKARİ', 'DEVLET'),
('fenerbahce-universitesi', 'FENERBAHÇE ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('istanbul-kultur-universitesi', 'İSTANBUL KÜLTÜR ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('bogazici-universitesi', 'BOĞAZİÇİ ÜNİVERSİTESİ', 'İSTANBUL', 'DEVLET'),
('erciyes-universitesi', 'ERCİYES ÜNİVERSİTESİ', 'KAYSERİ', 'DEVLET'),
('kocaeli-saglik-ve-teknoloji-universitesi', 'KOCAELİ SAĞLIK VE TEKNOLOJİ ÜNİVERSİTESİ', 'KOCAELİ', 'VAKIF'),
('afyon-kocatepe-universitesi', 'AFYON KOCATEPE ÜNİVERSİTESİ', 'AFYONKARAHİSAR', 'DEVLET'),
('istanbul-gedik-universitesi', 'İSTANBUL GEDİK ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('avrasya-universitesi', 'AVRASYA ÜNİVERSİTESİ', 'TRABZON', 'VAKIF'),
('marmara-universitesi', 'MARMARA ÜNİVERSİTESİ', 'İSTANBUL', 'DEVLET'),
('tokat-gaziosmanpasa-universitesi', 'TOKAT GAZİOSMANPAŞA ÜNİVERSİTESİ', 'TOKAT', 'DEVLET'),
('istanbul-topkapi-universitesi', 'İSTANBUL TOPKAPI ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('izmir-tinaztepe-universitesi', 'İZMİR TINAZTEPE ÜNİVERSİTESİ', 'İZMİR', 'VAKIF'),
('yeditepe-universitesi', 'YEDİTEPE ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('atilim-universitesi', 'ATILIM ÜNİVERSİTESİ', 'ANKARA', 'VAKIF'),
('istanbul-sabahattin-zaim-universitesi', 'İSTANBUL SABAHATTİN ZAİM ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('istinye-universitesi', 'İSTİNYE ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('bilecik-seyh-edebali-universitesi', 'BİLECİK ŞEYH EDEBALİ ÜNİVERSİTESİ', 'BİLECİK', 'DEVLET'),
('istanbul-saglik-ve-sosyal-bilimler-meslek-yuksekokulu', 'İSTANBUL SAĞLIK VE SOSYAL BİLİMLER MESLEK YÜKSEKOKULU', 'İSTANBUL', 'VAKIF   MYO'),
('sivas-cumhuriyet-universitesi', 'SİVAS CUMHURİYET ÜNİVERSİTESİ', 'SİVAS', 'DEVLET'),
('istanbul-saglik-ve-teknoloji-universitesi', 'İSTANBUL SAĞLIK VE TEKNOLOJİ ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('tarsus-universitesi', 'TARSUS ÜNİVERSİTESİ', 'MERSİN', 'DEVLET'),
('izmir-katip-celebi-universitesi', 'İZMİR KATİP ÇELEBİ ÜNİVERSİTESİ', 'İZMİR', 'DEVLET'),
('mudanya-universitesi', 'MUDANYA ÜNİVERSİTESİ', 'BURSA', 'VAKIF'),
('sakarya-universitesi', 'SAKARYA ÜNİVERSİTESİ', 'SAKARYA', 'DEVLET'),
('acibadem-mehmet-ali-aydinlar-universitesi', 'ACIBADEM MEHMET ALİ AYDINLAR ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('ankara-haci-bayram-veli-universitesi', 'ANKARA HACI BAYRAM VELİ ÜNİVERSİTESİ', 'ANKARA', 'DEVLET'),
('turk-alman-universitesi', 'TÜRK-ALMAN ÜNİVERSİTESİ', 'İSTANBUL', 'DEVLET'),
('sakarya-uygulamali-bilimler-universitesi', 'SAKARYA UYGULAMALI BİLİMLER ÜNİVERSİTESİ', 'SAKARYA', 'DEVLET'),
('erzincan-binali-yildirim-universitesi', 'ERZİNCAN BİNALİ YILDIRIM ÜNİVERSİTESİ', 'ERZİNCAN', 'DEVLET'),
('mugla-sitki-kocman-universitesi', 'MUĞLA SITKI KOÇMAN ÜNİVERSİTESİ', 'MUĞLA', 'DEVLET'),
('ankara-muzik-ve-guzel-sanatlar-universitesi', 'ANKARA MÜZİK VE GÜZEL SANATLAR ÜNİVERSİTESİ', 'ANKARA', 'DEVLET'),
('giresun-universitesi', 'GİRESUN ÜNİVERSİTESİ', 'GİRESUN', 'DEVLET'),
('mardin-artuklu-universitesi', 'MARDİN ARTUKLU ÜNİVERSİTESİ', 'MARDİN', 'DEVLET'),
('istanbul-rumeli-universitesi', 'İSTANBUL RUMELİ ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('sinop-universitesi', 'SİNOP ÜNİVERSİTESİ', 'SİNOP', 'DEVLET'),
('altinbas-universitesi', 'ALTINBAŞ ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('cukurova-universitesi', 'ÇUKUROVA ÜNİVERSİTESİ', 'ADANA', 'DEVLET'),
('trabzon-universitesi', 'TRABZON ÜNİVERSİTESİ', 'TRABZON', 'DEVLET'),
('galatasaray-universitesi', 'GALATASARAY ÜNİVERSİTESİ', 'İSTANBUL', 'DEVLET'),
('gazi-universitesi', 'GAZİ ÜNİVERSİTESİ', 'ANKARA', 'DEVLET'),
('istanbul-atlas-universitesi', 'İSTANBUL ATLAS ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('bitlis-eren-universitesi', 'BİTLİS EREN ÜNİVERSİTESİ', 'BİTLİS', 'DEVLET'),
('gaziantep-universitesi', 'GAZİANTEP ÜNİVERSİTESİ', 'GAZİANTEP', 'DEVLET'),
('kilis-7-aralik-universitesi', 'KİLİS 7 ARALIK ÜNİVERSİTESİ', 'KİLİS', 'DEVLET'),
('konya-gida-ve-tarim-universitesi', 'KONYA GIDA VE TARIM ÜNİVERSİTESİ', 'KONYA', 'VAKIF'),
('antalya-bilim-universitesi', 'ANTALYA BİLİM ÜNİVERSİTESİ', 'ANTALYA', 'VAKIF'),
('ardahan-universitesi', 'ARDAHAN ÜNİVERSİTESİ', 'ARDAHAN', 'DEVLET'),
('beykoz-universitesi', 'BEYKOZ ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('istanbul-kent-universitesi', 'İSTANBUL KENT ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('izmir-ekonomi-universitesi', 'İZMİR EKONOMİ ÜNİVERSİTESİ', 'İZMİR', 'VAKIF'),
('inonu-universitesi', 'İNÖNÜ ÜNİVERSİTESİ', 'MALATYA', 'DEVLET'),
('sivas-bilim-ve-teknoloji-universitesi', 'SİVAS BİLİM VE TEKNOLOJİ ÜNİVERSİTESİ', 'SİVAS', 'DEVLET'),
('sirnak-universitesi', 'ŞIRNAK ÜNİVERSİTESİ', 'ŞIRNAK', 'DEVLET'),
('recep-tayyip-erdogan-universitesi', 'RECEP TAYYİP ERDOĞAN ÜNİVERSİTESİ', 'RİZE', 'DEVLET'),
('istanbul-okan-universitesi', 'İSTANBUL OKAN ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('lokman-hekim-universitesi', 'LOKMAN HEKİM ÜNİVERSİTESİ', 'ANKARA', 'VAKIF'),
('malatya-turgut-ozal-universitesi', 'MALATYA TURGUT ÖZAL ÜNİVERSİTESİ', 'MALATYA', 'DEVLET'),
('ordu-universitesi', 'ORDU ÜNİVERSİTESİ', 'ORDU', 'DEVLET'),
('abdullah-gul-universitesi', 'ABDULLAH GÜL ÜNİVERSİTESİ', 'KAYSERİ', 'DEVLET'),
('afyonkarahisar-saglik-bilimleri-universitesi', 'AFYONKARAHİSAR SAĞLIK BİLİMLERİ ÜNİVERSİTESİ', 'AFYONKARAHİSAR', 'DEVLET'),
('gaziantep-islam-bilim-ve-teknoloji-universitesi', 'GAZİANTEP İSLAM BİLİM VE TEKNOLOJİ ÜNİVERSİTESİ', 'GAZİANTEP', 'DEVLET'),
('usak-universitesi', 'UŞAK ÜNİVERSİTESİ', 'UŞAK', 'DEVLET'),
('bursa-teknik-universitesi', 'BURSA TEKNİK ÜNİVERSİTESİ', 'BURSA', 'DEVLET'),
('ibn-haldun-universitesi', 'İBN HALDUN ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('istanbul-ticaret-universitesi', 'İSTANBUL TİCARET ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('mersin-universitesi', 'MERSİN ÜNİVERSİTESİ', 'MERSİN', 'DEVLET'),
('ankara-yildirim-beyazit-universitesi', 'ANKARA YILDIRIM BEYAZIT ÜNİVERSİTESİ', 'ANKARA', 'DEVLET'),
('duzce-universitesi', 'DÜZCE ÜNİVERSİTESİ', 'DÜZCE', 'DEVLET'),
('kutahya-saglik-bilimleri-universitesi', 'KÜTAHYA SAĞLIK BİLİMLERİ ÜNİVERSİTESİ', 'KÜTAHYA', 'DEVLET'),
('munzur-universitesi', 'MUNZUR ÜNİVERSİTESİ', 'TUNCELİ', 'DEVLET'),
('agri-ibrahim-cecen-universitesi', 'AĞRI İBRAHİM ÇEÇEN ÜNİVERSİTESİ', 'AĞRI', 'DEVLET'),
('ataturk-universitesi', 'ATATÜRK ÜNİVERSİTESİ', 'ERZURUM', 'DEVLET'),
('konya-teknik-universitesi', 'KONYA TEKNİK ÜNİVERSİTESİ', 'KONYA', 'DEVLET'),
('samsun-universitesi', 'SAMSUN ÜNİVERSİTESİ', 'SAMSUN', 'DEVLET'),
('dicle-universitesi', 'DİCLE ÜNİVERSİTESİ', 'DİYARBAKIR', 'DEVLET'),
('kirikkale-universitesi', 'KIRIKKALE ÜNİVERSİTESİ', 'KIRIKKALE', 'DEVLET'),
('turk-hava-kurumu-universitesi', 'TÜRK HAVA KURUMU ÜNİVERSİTESİ', 'ANKARA', 'VAKIF'),
('kutahya-dumlupinar-universitesi', 'KÜTAHYA DUMLUPINAR ÜNİVERSİTESİ', 'KÜTAHYA', 'DEVLET'),
('bursa-uludag-universitesi', 'BURSA ULUDAĞ ÜNİVERSİTESİ', 'BURSA', 'DEVLET'),
('hasan-kalyoncu-universitesi', 'HASAN KALYONCU ÜNİVERSİTESİ', 'GAZİANTEP', 'VAKIF'),
('istanbul-nisantasi-universitesi', 'İSTANBUL NİŞANTAŞI ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('biruni-universitesi', 'BİRUNİ ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('fatih-sultan-mehmet-vakif-universitesi', 'FATİH SULTAN MEHMET VAKIF ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('ankara-bilim-universitesi', 'ANKARA BİLİM ÜNİVERSİTESİ', 'ANKARA', 'VAKIF'),
('ankara-sosyal-bilimler-universitesi', 'ANKARA SOSYAL BİLİMLER ÜNİVERSİTESİ', 'KIBRIS', 'DEVLET'),
('karabuk-universitesi', 'KARABÜK ÜNİVERSİTESİ', 'KARABÜK', 'DEVLET'),
('karamanoglu-mehmetbey-universitesi', 'KARAMANOĞLU MEHMETBEY ÜNİVERSİTESİ', 'KARAMAN', 'DEVLET'),
('eskisehir-teknik-universitesi', 'ESKİŞEHİR TEKNİK ÜNİVERSİTESİ', 'ESKİŞEHİR', 'DEVLET'),
('harran-universitesi', 'HARRAN ÜNİVERSİTESİ', 'ŞANLIURFA', 'DEVLET'),
('istanbul-29-mayis-universitesi', 'İSTANBUL 29 MAYIS ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('kahramanmaras-sutcu-imam-universitesi', 'KAHRAMANMARAŞ SÜTÇÜ İMAM ÜNİVERSİTESİ', 'KAHRAMANMARAŞ', 'DEVLET'),
('necmettin-erbakan-universitesi', 'NECMETTİN ERBAKAN ÜNİVERSİTESİ', 'KONYA', 'DEVLET'),
('adana-alparslan-turkes-bilim-ve-teknoloji-universitesi', 'ADANA ALPARSLAN TÜRKEŞ BİLİM VE TEKNOLOJİ ÜNİVERSİTESİ', 'ADANA', 'DEVLET'),
('bolu-abant-izzet-baysal-universitesi', 'BOLU ABANT İZZET BAYSAL ÜNİVERSİTESİ', 'BOLU', 'DEVLET'),
('cankiri-karatekin-universitesi', 'ÇANKIRI KARATEKİN ÜNİVERSİTESİ', 'ÇANKIRI', 'DEVLET'),
('pamukkale-universitesi', 'PAMUKKALE ÜNİVERSİTESİ', 'DENİZLİ', 'DEVLET'),
('kayseri-universitesi', 'KAYSERİ ÜNİVERSİTESİ', 'KAYSERİ', 'DEVLET'),
('sanko-universitesi', 'SANKO ÜNİVERSİTESİ', 'GAZİANTEP', 'VAKIF'),
('cag-universitesi', 'ÇAĞ ÜNİVERSİTESİ', 'MERSİN', 'VAKIF'),
('gebze-teknik-universitesi', 'GEBZE TEKNİK ÜNİVERSİTESİ', 'KOCAELİ', 'DEVLET'),
('hacettepe-universitesi', 'HACETTEPE ÜNİVERSİTESİ', 'ANKARA', 'DEVLET'),
('yozgat-bozok-universitesi', 'YOZGAT BOZOK ÜNİVERSİTESİ', 'YOZGAT', 'DEVLET'),
('batman-universitesi', 'BATMAN ÜNİVERSİTESİ', 'BATMAN', 'DEVLET'),
('istanbul-medipol-universitesi', 'İSTANBUL MEDİPOL ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('kirsehir-ahi-evran-universitesi', 'KIRŞEHİR AHİ EVRAN ÜNİVERSİTESİ', 'KIRŞEHİR', 'DEVLET'),
('istanbul-sisli-meslek-yuksekokulu', 'İSTANBUL ŞİŞLİ MESLEK YÜKSEKOKULU', 'İSTANBUL', 'VAKIF   MYO'),
('artvin-coruh-universitesi', 'ARTVİN ÇORUH ÜNİVERSİTESİ', 'ARTVİN', 'DEVLET'),
('bezm-i-alem-vakif-universitesi', 'BEZM-İ ÂLEM VAKIF ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('isparta-uygulamali-bilimler-universitesi', 'ISPARTA UYGULAMALI BİLİMLER ÜNİVERSİTESİ', 'ISPARTA', 'DEVLET'),
('istanbul-teknik-universitesi', 'İSTANBUL TEKNİK ÜNİVERSİTESİ', 'İSTANBUL', 'DEVLET'),
('manisa-celal-bayar-universitesi', 'MANİSA CELÂL BAYAR ÜNİVERSİTESİ', 'MANİSA', 'DEVLET'),
('nigde-omer-halisdemir-universitesi', 'NİĞDE ÖMER HALİSDEMİR ÜNİVERSİTESİ', 'NİĞDE', 'DEVLET'),
('trakya-universitesi', 'TRAKYA ÜNİVERSİTESİ', 'EDİRNE', 'DEVLET'),
('adiyaman-universitesi', 'ADIYAMAN ÜNİVERSİTESİ', 'ADIYAMAN', 'DEVLET'),
('cankaya-universitesi', 'ÇANKAYA ÜNİVERSİTESİ', 'ANKARA', 'VAKIF'),
('mus-alparslan-universitesi', 'MUŞ ALPARSLAN ÜNİVERSİTESİ', 'MUŞ', 'DEVLET'),
('osmaniye-korkut-ata-universitesi', 'OSMANİYE KORKUT ATA ÜNİVERSİTESİ', 'OSMANİYE', 'DEVLET'),
('akdeniz-universitesi', 'AKDENİZ ÜNİVERSİTESİ', 'ANTALYA', 'DEVLET'),
('izmir-bakircay-universitesi', 'İZMİR BAKIRÇAY ÜNİVERSİTESİ', 'İZMİR', 'DEVLET'),
('izmir-demokrasi-universitesi', 'İZMİR DEMOKRASİ ÜNİVERSİTESİ', 'İZMİR', 'DEVLET'),
('toros-universitesi', 'TOROS ÜNİVERSİTESİ', 'MERSİN', 'VAKIF'),
('antalya-belek-universitesi', 'ANTALYA BELEK ÜNİVERSİTESİ', 'ANTALYA', 'VAKIF'),
('kafkas-universitesi', 'KAFKAS ÜNİVERSİTESİ', 'KARS', 'DEVLET'),
('ostim-teknik-universitesi', 'OSTİM TEKNİK ÜNİVERSİTESİ', 'ANKARA', 'VAKIF'),
('istanbul-universitesi-cerrahpasa', 'İSTANBUL ÜNİVERSİTESİ-CERRAHPAŞA', 'İSTANBUL', 'DEVLET'),
('izmir-yuksek-teknoloji-enstitusu', 'İZMİR YÜKSEK TEKNOLOJİ ENSTİTÜSÜ', 'İZMİR', 'DEVLET'),
('yildiz-teknik-universitesi', 'YILDIZ TEKNİK ÜNİVERSİTESİ', 'İSTANBUL', 'DEVLET'),
('ankara-medipol-universitesi', 'ANKARA MEDİPOL ÜNİVERSİTESİ', 'ANKARA', 'VAKIF'),
('dogus-universitesi', 'DOĞUŞ ÜNİVERSİTESİ', 'İSTANBUL', 'VAKIF'),
('gumushane-universitesi', 'GÜMÜŞHANE ÜNİVERSİTESİ', 'GÜMÜŞHANE', 'DEVLET'),
('ondokuz-mayis-universitesi', 'ONDOKUZ MAYIS ÜNİVERSİTESİ', 'SAMSUN', 'DEVLET'),
('selcuk-universitesi', 'SELÇUK ÜNİVERSİTESİ', 'KONYA', 'DEVLET');
